### ISSUE TITLE
Plugin looks strange

### ISSUE THREAD

**Issue by Eyecatcher00** [klangfarbe/Go-for-WordPress#8]
Hi, my plugin looks not ok :-/ Maybe you can help me to fix the problem. 
My wordpress etc. is last version... 
cheers
![bildschirmfoto 2015-10-11 um 21 00 35](https://cloud.githubusercontent.com/assets/10393622/10418437/7b751344-705b-11e5-8a62-5c0a96eb2916.png)

**Comment by klangfarbe** [comment]
Hi,

sorry for the late response. I had a quick check in my local installation and the problem appears to be an CSS issue with the new default Wordpress themes in conjunction with the wgo.js CSS. I will try to fix this.

**Comment by Eyecatcher00** [comment]
hi, thank you! 
good luck, greetings, 
amon

Von meinem iPad gesendet

**Comment by klangfarbe** [comment]
Should be fixed in version 0.5
